In [1]:
"""1. Create a null vector of size 10 but the fifth value which is 1 
2. Create a vector with values ranging from 10 to 49
3. Reverse a vector
4. Create a 3x3 matrix with values ranging from 0 to 8
5. Find indices of non-zero elements from [1,2,0,0,4,0]
6. Create a 3x3x3 array with random values
7. Create a 10x10 array with random values and find the minimum and maximum values
8. Create a 2d array with 1 on the border and 0 inside
"""

'1. Create a null vector of size 10 but the fifth value which is 1 \n2. Create a vector with values ranging from 10 to 49\n3. Reverse a vector\n4. Create a 3x3 matrix with values ranging from 0 to 8\n5. Find indices of non-zero elements from [1,2,0,0,4,0]\n6. Create a 3x3x3 array with random values\n7. Create a 10x10 array with random values and find the minimum and maximum values\n8. Create a 2d array with 1 on the border and 0 inside\n'

In [2]:
import numpy as np

In [7]:
arr=np.zeros(10)

In [9]:
arr[4]=1

In [10]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
arr1=np.arange(10,50)

In [12]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
arr1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [19]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
list1=[1,2,0,0,4,0]
[i for i in range(len(list1)) if list1[i]>0]

[0, 1, 4]

In [16]:
array_3x3x3 = np.random.rand(3, 3, 3)
print( array_3x3x3)

Task 1:
 [[[0.44465873 0.49978599 0.5080546 ]
  [0.28520955 0.36179304 0.87569946]
  [0.50235601 0.19719368 0.17724601]]

 [[0.41659366 0.89991796 0.40818767]
  [0.46535652 0.02805111 0.68455749]
  [0.8106411  0.35074093 0.32695307]]

 [[0.03594012 0.39655789 0.18493328]
  [0.20076844 0.43860493 0.23056049]
  [0.21638207 0.28535308 0.77304865]]]


In [17]:
array_10x10 = np.random.rand(10, 10)
min_value = np.min(array_10x10)
max_value = np.max(array_10x10)
print( array_10x10)
print("\n Minimum value:", min_value)
print("\n Max", max_value)

[[0.30107131 0.27246163 0.64698617 0.83928996 0.18783736 0.96032741
  0.55402208 0.64208121 0.7589999  0.34125462]
 [0.41522589 0.71816943 0.69190669 0.50316739 0.73574346 0.84653773
  0.94202957 0.50822405 0.40886272 0.66968682]
 [0.22192476 0.90256859 0.2707004  0.77661016 0.02292032 0.06181386
  0.61163969 0.71347363 0.79766292 0.86362028]
 [0.92907195 0.43918104 0.61852937 0.27953792 0.72849804 0.91208868
  0.03219661 0.57840381 0.53326952 0.96664942]
 [0.2356165  0.96758809 0.29000552 0.6671144  0.43760186 0.72584634
  0.91148963 0.82503139 0.61639888 0.89265037]
 [0.60418566 0.08422383 0.23445633 0.9187105  0.26592514 0.8998246
  0.89519053 0.39468936 0.5033398  0.61792086]
 [0.93135385 0.46609402 0.4367665  0.90264037 0.6025392  0.23518066
  0.27719874 0.2878692  0.4203749  0.87497164]
 [0.30254659 0.64840929 0.2272291  0.54140033 0.2369977  0.77800074
  0.3341695  0.30596435 0.39655398 0.91934373]
 [0.69480635 0.96663878 0.57288329 0.94530605 0.54230711 0.69331375
  0.00962996 

In [18]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print("\nTask 3:\n", array_2d)


Task 3:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
